user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("layout.css.has-selector.enabled", true);
user_pref("browser.display.background_color", "#eee");
user_pref("browser.display.background_color.dark", "#222");
user_pref("browser.tabs.searchclipboardfor.middleclick", false);
user_pref("toolkit.tabbox.switchByScrolling", true);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.tabs.groups.enabled", true);
